# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyZkqYxfb4OtpoUZ95wXTJjGsHdGOO2z
"""

caminho = 'Entregas.xlsx'

import pandas as pd
import streamlit as st

df_entregas = pd.read_excel(caminho).fillna(0)
df_entregas['Ecoscoting'] = df_entregas['Ecoscoting'].astype(int)
df_entregas['Mês'] = df_entregas['Data'].dt.month_name()

valor_paack = float(0.80)
valor_ecoscoting = float(0.60)
conveu = float(5.88)

df_entregas['qtdias'] = df_entregas['Data'].value_counts()
df_entregas['count_dias'] = df_entregas['qtdias'].fillna(1).astype(int)
df_entregas['Total Paack'] = df_entregas['Paack']*valor_paack
df_entregas['Total Ecoscoting'] = df_entregas['Ecoscoting']*valor_ecoscoting
df_entregas['Total'] = df_entregas['Total Paack'] + df_entregas['Total Ecoscoting']
df_entregas['Total Conv'] = df_entregas['Total']*conveu




tabela = df_entregas.groupby('Mês')[['count_dias','Paack','Ecoscoting','Total Paack','Total Ecoscoting', 'Total', 'Total Conv' ]].sum().reset_index()

st.title('Dashboard de Entregas')

st.dataframe(tabela)

st.bar_chart(tabela.set_index('Mês')[['Paack', 'Ecoscoting']])